# **Battle of Neighbpurhood**

## **Introduction**

ABC is a company based in Toronto for organizing events, currently it works on a project to organize an event for 5 days for a group of photographers from all over the world.The company has to put a good program, including a hotel of residence, a hall for meetings, 
places of landscape to visit, stores for shopping, restaurants and cafes. So the company’s purpose is to make a list of places of landscape in Toronto, including the nearest restaurants, cafes, and shopping stores for each place.

## **Data Description**

The data used in this project is provided by Foursquare location data. The data are grouped by landscape area, and each area included the information about this area and all information about restaurants, cafes, and stores which in this area.

## **Table of contents**

#### 01- Import Libraries
#### 02- Define Foursquare Credentials
#### 03- Define the city and get its latitude & longitude
#### 04- Search for Hotels & clean dataframe
#### 05- Search for Parks & clean dataframe
#### 06- Search for Restaurants & clean dataframe
#### 07- Search for Cafeteria & clean dataframe 
#### 08- Search for Shopping Stores & clean dataframe
#### 09- Generate map to visualize hotels, shopping stores and Cafeteria and how they cluster together
#### 10- Generate map to visualize Park, Restaurant and Cafeteria and how they cluster together

## **Import Libraries**

In [1]:
import requests # to handle requests
import pandas as pd # for data analsysis
import numpy as np # to handle data in a vectorized manner

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
#tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

Solving environment: done

# All requested packages already installed.

Solving environment: done

# All requested packages already installed.

## **Define Foursquare Credentials**

In [2]:
ClIENT_ID = '4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK' # your Foursquare ID
ClIENT_SECRET = 'AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG' # your Foursquare Secret
VERSION = '20180604'
LIMIT =30
print('Your credentails:')
print('Foursquare_ID: ' + ClIENT_ID)
print('Foursquare_Secret:' + ClIENT_SECRET)

Your credentails:
Foursquare_ID: 4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK
Foursquare_Secret:AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG

## **Define the city and get its latitude & longitude**

In [3]:
# define the city and get its latitude & longitude 
city = 'Toronto'
geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(city)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

43.653963 -79.387207

## **Search for Hotels**

In [4]:
# search for hotels
search_query = 'Hotel'
radius = 500

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK&client_secret=AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG&ll=43.653963,-79.387207&v=20180604&query=Hotel&radius=500&limit=30'

In [5]:
# Send the GET Request and examine the results
results = requests.get(url).json()
#results

In [6]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'name': 'Hotel', 'pluralName': 'Hotels', 'ic...",False,4ab2d511f964a5209b6c20e3,123 Queen Street West,CA,Toronto,Canada,at York St.,416,"[123 Queen Street West (at York St.), Toronto ...","[{'lat': 43.651129283252786, 'label': 'display...",43.651129,-79.383829,NaN,M5H 2M9,ON,Sheraton Centre Toronto Hotel,v-1558854553,NaN
1,"[{'name': 'Jazz Club', 'pluralName': 'Jazz Clu...",False,4b68aed1f964a520de862be3,194 Queen St W,CA,Toronto,Canada,Queen & St. Patrick,400,"[194 Queen St W (Queen & St. Patrick), Toronto...","[{'lat': 43.65050475544005, 'label': 'display'...",43.650505,-79.388577,NaN,M5V 1Z1,ON,The Rex Hotel Jazz & Blues Bar,v-1558854553,62225795
2,"[{'name': 'Hotel', 'pluralName': 'Hotels', 'ic...",False,58b7d72dcc05d161570bd712,123 Queen Street West,CA,Toronto,Canada,NaN,410,"[123 Queen Street West, Toronto ON M5H 2M9, Ca...","[{'lat': 43.65101646682632, 'label': 'display'...",43.651016,-79.384148,NaN,M5H 2M9,ON,Sheraton Centre Toronto Hotel,v-1558854553,402127087
3,"[{'name': 'Hotel', 'pluralName': 'Hotels', 'ic...",False,52ce14b0498e50457ce11780,108 Chestnut Street,CA,Toronto,Canada,Dundas St W,124,"[108 Chestnut Street (Dundas St W), Toronto ON...","[{'lat': 43.6546083, 'label': 'display', 'lng'...",43.654608,-79.385942,NaN,M5G 1R3,ON,DoubleTree by Hilton Hotel Toronto Downtown,v-1558854553,NaN
4,"[{'name': 'Hotel', 'pluralName': 'Hotels', 'ic...",False,4f343a31e4b0230a3b337a90,123 Test Drive,CA,Toronto,Canada,at somewhere St,500,"[123 Test Drive (at somewhere St), Toronto ON ...","[{'lat': 43.658434, 'label': 'display', 'lng':...",43.658434,-79.387894,NaN,M2M 2M2,ON,VFM Test Hotel,v-1558854553,NaN

## **Clean Hotel Dataframe**

In [7]:
# keep only columns that include venue name, and anything that is associated with location
clean_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')]+ ['id']
clean_dataframe = dataframe.loc[:,clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
clean_dataframe['categories'] = clean_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_dataframe.columns = [column.split('.')[-1] for column in clean_dataframe.columns]

clean_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,neighborhood,postalCode,state,id
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,CA,Toronto,Canada,at York St.,416,"[123 Queen Street West (at York St.), Toronto ...","[{'lat': 43.651129283252786, 'label': 'display...",43.651129,-79.383829,NaN,M5H 2M9,ON,4ab2d511f964a5209b6c20e3
1,The Rex Hotel Jazz & Blues Bar,Jazz Club,194 Queen St W,CA,Toronto,Canada,Queen & St. Patrick,400,"[194 Queen St W (Queen & St. Patrick), Toronto...","[{'lat': 43.65050475544005, 'label': 'display'...",43.650505,-79.388577,NaN,M5V 1Z1,ON,4b68aed1f964a520de862be3
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,CA,Toronto,Canada,NaN,410,"[123 Queen Street West, Toronto ON M5H 2M9, Ca...","[{'lat': 43.65101646682632, 'label': 'display'...",43.651016,-79.384148,NaN,M5H 2M9,ON,58b7d72dcc05d161570bd712
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,CA,Toronto,Canada,Dundas St W,124,"[108 Chestnut Street (Dundas St W), Toronto ON...","[{'lat': 43.6546083, 'label': 'display', 'lng'...",43.654608,-79.385942,NaN,M5G 1R3,ON,52ce14b0498e50457ce11780
4,VFM Test Hotel,Hotel,123 Test Drive,CA,Toronto,Canada,at somewhere St,500,"[123 Test Drive (at somewhere St), Toronto ON ...","[{'lat': 43.658434, 'label': 'display', 'lng':...",43.658434,-79.387894,NaN,M2M 2M2,ON,4f343a31e4b0230a3b337a90

In [8]:
# delete unnecessary columns
clean_dataframe2= clean_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs','neighborhood', 'id'], axis=1)
clean_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
1,The Rex Hotel Jazz & Blues Bar,Jazz Club,194 Queen St W,43.650505,-79.388577,M5V 1Z1,ON
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651016,-79.384148,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
5,Sheraton Centre Toronto Hotel - Grand Ballroom,Ballroom,123 Queen Street West,43.651200,-79.384520,NaN,ON
6,Stathcona Hotel,Hotel,NaN,43.654947,-79.386359,NaN,ON
7,"hilton hotel, richmondstreet E, 145, toronto",Hotel Pool,"Richmondstreet E, 145",43.650625,-79.385488,NaN,ON
8,Be SixFifty Hotel,Hotel,650 Bay Street,43.657120,-79.384560,NaN,ON
9,650 Hotel,Hotel,650 Bay Street,43.657046,-79.384411,NaN,ON
10,Hilton Toronto,Hotel,145 Richmond St W,43.649852,-79.385576,M5H 2L2,ON
11,89 Chestnut Residence,College Residence Hall,89 Chestnut St.,43.654160,-79.385291,M5G 1R1,ON
12,Lobby Lounge at the Shangri-La Toronto,Lounge,188 University Ave.,43.649155,-79.386546,M5H 0A3,ON
13,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
14,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
15,Op mijn hotelkamer In Toronto,Hotel,NaN,43.654235,-79.386208,NaN,ON
16,Fitness Centre,Gym,525 Bay St.,43.654690,-79.381739,M5G 2L2,ON
17,Bistro on Two,Breakfast Spot,123 Queen St. W,43.651011,-79.383658,M5H 2M9,ON
18,Pool,Pool,Intercontinental,43.650975,-79.384053,NaN,Ontario
19,Kumar For Men,Men's Store,Sheraton Centre,43.651044,-79.383302,M5H 2M9,ON
20,Fitness Centre,Gym,Sheraton Centre,43.650985,-79.384002,M5H 2M9,ON
21,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

In [9]:
# delete rows with none values
clean_dataframe3 = clean_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
1,The Rex Hotel Jazz & Blues Bar,Jazz Club,194 Queen St W,43.650505,-79.388577,M5V 1Z1,ON
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651016,-79.384148,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
10,Hilton Toronto,Hotel,145 Richmond St W,43.649852,-79.385576,M5H 2L2,ON
11,89 Chestnut Residence,College Residence Hall,89 Chestnut St.,43.654160,-79.385291,M5G 1R1,ON
12,Lobby Lounge at the Shangri-La Toronto,Lounge,188 University Ave.,43.649155,-79.386546,M5H 0A3,ON
13,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
14,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
16,Fitness Centre,Gym,525 Bay St.,43.654690,-79.381739,M5G 2L2,ON
17,Bistro on Two,Breakfast Spot,123 Queen St. W,43.651011,-79.383658,M5H 2M9,ON
19,Kumar For Men,Men's Store,Sheraton Centre,43.651044,-79.383302,M5H 2M9,ON
20,Fitness Centre,Gym,Sheraton Centre,43.650985,-79.384002,M5H 2M9,ON
21,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

In [10]:
# delete rows which its category is not Hotel or Event Space
array= ['Hotel', 'Event Space']
hotel_dataframe= clean_dataframe3.loc[clean_dataframe3['categories'].isin(array)]
hotel_dataframe

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
2,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651016,-79.384148,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
10,Hilton Toronto,Hotel,145 Richmond St W,43.649852,-79.385576,M5H 2L2,ON
13,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
14,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
21,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

In [11]:
# delete rows which has duplicate hotel's name
df_hotels = hotel_dataframe.drop_duplicates(subset='name', keep="first")
df_hotels

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
3,DoubleTree by Hilton Hotel Toronto Downtown,Hotel,108 Chestnut Street,43.654608,-79.385942,M5G 1R3,ON
4,VFM Test Hotel,Hotel,123 Test Drive,43.658434,-79.387894,M2M 2M2,ON
10,Hilton Toronto,Hotel,145 Richmond St W,43.649852,-79.385576,M5H 2L2,ON
13,Marriott Downtown at CF Toronto Eaton Centre,Hotel,525 Bay Street,43.654728,-79.382422,M5G 2L2,ON
14,Shangri-La Toronto,Hotel,188 University Ave.,43.649129,-79.386557,M5H 0A3,ON
21,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

In [12]:
# choose the hotel which has the same postalCode with the event space
df_hotel = df_hotels[df_hotels.postalCode == 'M5H 2M9']
df_hotel

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
21,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON

## **Search for Parks**

In [13]:
# search for Parks
search_query = 'Park'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK&client_secret=AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG&ll=43.653963,-79.387207&v=20180604&query=Park&radius=10000&limit=30'

In [14]:
# Send the GET Request and examine the results
presults = requests.get(url).json()
#presults

In [15]:
# assign relevant part of JSON to venues
venues = presults['response']['venues']

# tranform venues into a dataframe
park_dataframe = json_normalize(venues)
park_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'name': 'Metro Station', 'pluralName': 'Metr...",False,4b170e47f964a5208cc123e3,691 University Ave,CA,Toronto,Canada,at College St,716,"[691 University Ave (at College St), Toronto O...","[{'lat': 43.660006357009195, 'label': 'display...",43.660006,-79.390272,M5G 2P1,ON,Queen's Park Subway Station,v-1558854590,NaN
1,"[{'name': 'Park', 'pluralName': 'Parks', 'icon...",False,4b54deadf964a520a3d027e3,NaN,CA,Toronto,Canada,NaN,423,"[btwn College, University, Queen & Spadina, To...","[{'lat': 43.652487552998565, 'label': 'display...",43.652488,-79.392053,NaN,ON,Grange Park,v-1558854590,NaN
2,"[{'name': 'Gym / Fitness Center', 'pluralName'...",False,59ddd7469ba3e51a75459568,382 Yonge Street,CA,Toronto,Canada,NaN,695,"[382 Yonge Street, Toronto ON M5G 1S8, Canada]","[{'lat': 43.6592634, 'label': 'display', 'lng'...",43.659263,-79.382632,M5G 1S8,ON,Crunch Fitness - College Park,v-1558854590,532736199
3,[{'name': 'Residential Building (Apartment / C...,False,4ad80fcef964a520a61021e3,280 Simcoe St,CA,Toronto,Canada,Dundas Street West,282,"[280 Simcoe St (Dundas Street West), Toronto O...","[{'lat': 43.65544241747622, 'label': 'display'...",43.655442,-79.390056,M5T 2Y5,ON,One Park Lane,v-1558854590,NaN
4,"[{'name': 'Park', 'pluralName': 'Parks', 'icon...",False,4ad4c05ef964a520bdf620e3,1053 Dundas St. W.,CA,Toronto,Canada,at Gore Vale Ave.,2271,"[1053 Dundas St. W. (at Gore Vale Ave.), Toron...","[{'lat': 43.64707192840234, 'label': 'display'...",43.647072,-79.413756,M5H 2N2,ON,Trinity Bellwoods Park,v-1558854590,NaN

## **Clean Park Dataframe**

In [17]:
# keep only columns that include venue name, and anything that is associated with location
park_clean_columns = ['name', 'categories'] + [col for col in park_dataframe.columns if col.startswith('location.')]+ ['id']
clean_park_dataframe = park_dataframe.loc[:,park_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list1 = row['categories']
    except:
        categories_list1 = row['venue.categories']
        
    if len(categories_list1) == 0:
        return None
    else:
        return categories_list1[0]['name']

# filter the category for each row
clean_park_dataframe['categories'] = clean_park_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_park_dataframe.columns = [column.split('.')[-1] for column in clean_park_dataframe.columns]

clean_park_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,Queen's Park Subway Station,Metro Station,691 University Ave,CA,Toronto,Canada,at College St,716,"[691 University Ave (at College St), Toronto O...","[{'lat': 43.660006357009195, 'label': 'display...",43.660006,-79.390272,M5G 2P1,ON,4b170e47f964a5208cc123e3
1,Grange Park,Park,NaN,CA,Toronto,Canada,NaN,423,"[btwn College, University, Queen & Spadina, To...","[{'lat': 43.652487552998565, 'label': 'display...",43.652488,-79.392053,NaN,ON,4b54deadf964a520a3d027e3
2,Crunch Fitness - College Park,Gym / Fitness Center,382 Yonge Street,CA,Toronto,Canada,NaN,695,"[382 Yonge Street, Toronto ON M5G 1S8, Canada]","[{'lat': 43.6592634, 'label': 'display', 'lng'...",43.659263,-79.382632,M5G 1S8,ON,59ddd7469ba3e51a75459568
3,One Park Lane,Residential Building (Apartment / Condo),280 Simcoe St,CA,Toronto,Canada,Dundas Street West,282,"[280 Simcoe St (Dundas Street West), Toronto O...","[{'lat': 43.65544241747622, 'label': 'display'...",43.655442,-79.390056,M5T 2Y5,ON,4ad80fcef964a520a61021e3
4,Trinity Bellwoods Park,Park,1053 Dundas St. W.,CA,Toronto,Canada,at Gore Vale Ave.,2271,"[1053 Dundas St. W. (at Gore Vale Ave.), Toron...","[{'lat': 43.64707192840234, 'label': 'display'...",43.647072,-79.413756,M5H 2N2,ON,4ad4c05ef964a520bdf620e3

In [18]:
# delete unnecessary columns
clean_park_dataframe2= clean_park_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_park_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Queen's Park Subway Station,Metro Station,691 University Ave,43.660006,-79.390272,M5G 2P1,ON
1,Grange Park,Park,NaN,43.652488,-79.392053,NaN,ON
2,Crunch Fitness - College Park,Gym / Fitness Center,382 Yonge Street,43.659263,-79.382632,M5G 1S8,ON
3,One Park Lane,Residential Building (Apartment / Condo),280 Simcoe St,43.655442,-79.390056,M5T 2Y5,ON
4,Trinity Bellwoods Park,Park,1053 Dundas St. W.,43.647072,-79.413756,M5H 2N2,ON
5,Clarence Square Park,Park,Spadina Ave,43.644222,-79.394230,NaN,ON
6,Queen's Park,Park,University Ave.,43.663946,-79.392180,M5R 2E8,ON
7,St. Andrews Playground / Dog Park,Park,450 Adelaide Street West,43.647388,-79.398752,NaN,ON
8,Bellevue Square Park,Park,btwn Bellevue & Augusta Ave.,43.653610,-79.402199,M5T 2N4,ON
9,Berczy Park,Park,35 Wellington St. East,43.648048,-79.375172,NaN,ON
10,HTO Park,Park,Queen's Quay,43.637949,-79.387820,NaN,ON
11,Residences at College Park North,Residential Building (Apartment / Condo),763 Bay St.,43.659822,-79.385159,M5G 2R3,ON
12,High Park,Park,1873 Bloor St. W,43.646479,-79.463425,M6R 2Z3,ON
13,TTC Streetcar #403 - Victoria park,Light Rail Station,NaN,43.650735,-79.386921,NaN,ON
14,Parliament Square Park,Park,44 Parliament Street,43.650264,-79.362195,NaN,ON
15,Stanley Park (Dog Park),Dog Run,King Street West,43.641668,-79.409269,NaN,ON
16,Physiomed College Park,Medical Center,382 Yonge St,43.658528,-79.382169,M5B 1S8,ON
17,Winchester Park,Playground,530 Ontario Street,43.666231,-79.371631,NaN,ON
18,Riverdale Park West,Park,500 Gerrard St.,43.666048,-79.360941,M5A 2H3,ON
19,Battery Park Tower,Residential Building (Apartment / Condo),50 Lynn Williams St,43.639024,-79.415510,M6K 3R9,ON
20,GoodLife Fitness Toronto Bloor Park,Gym,8 Park Rd,43.671398,-79.384408,M4W 3G8,ON
21,Riverdale Park East,Park,550 Broadview Ave,43.669951,-79.355493,M4K 2P1,ON
22,Cawthra Square Dog Park,Dog Run,519 Church St.,43.666583,-79.380040,NaN,ON
23,Toothworks - College Park Dental,Dentist's Office,"444 Yonge St, Unit M16",43.660009,-79.383905,NaN,ON
24,Stanley Park,Park,King Street West,43.642395,-79.409330,NaN,ON
25,Victoria Park Subway Station,Metro Station,777 Victoria Park Ave,43.694883,-79.288735,M4B 2E2,ON
26,Coronation Park,Park,711 Lake Shore Blvd. W,43.634553,-79.405403,M5V 3T7,ON
27,Canoe Landing Park,Park,50 Fort York Blvd,43.638762,-79.397067,M5V 3Z1,ON
28,Barbara Hall Park,Park,519 Church St,43.666879,-79.381068,M4Y 2K9,ON
29,Regent Park,Neighborhood,NaN,43.660015,-79.363114,NaN,ON

In [19]:
# delete rows with none values
clean_park_dataframe3 = clean_park_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_park_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,Queen's Park Subway Station,Metro Station,691 University Ave,43.660006,-79.390272,M5G 2P1,ON
2,Crunch Fitness - College Park,Gym / Fitness Center,382 Yonge Street,43.659263,-79.382632,M5G 1S8,ON
3,One Park Lane,Residential Building (Apartment / Condo),280 Simcoe St,43.655442,-79.390056,M5T 2Y5,ON
4,Trinity Bellwoods Park,Park,1053 Dundas St. W.,43.647072,-79.413756,M5H 2N2,ON
6,Queen's Park,Park,University Ave.,43.663946,-79.392180,M5R 2E8,ON
8,Bellevue Square Park,Park,btwn Bellevue & Augusta Ave.,43.653610,-79.402199,M5T 2N4,ON
11,Residences at College Park North,Residential Building (Apartment / Condo),763 Bay St.,43.659822,-79.385159,M5G 2R3,ON
12,High Park,Park,1873 Bloor St. W,43.646479,-79.463425,M6R 2Z3,ON
16,Physiomed College Park,Medical Center,382 Yonge St,43.658528,-79.382169,M5B 1S8,ON
18,Riverdale Park West,Park,500 Gerrard St.,43.666048,-79.360941,M5A 2H3,ON
19,Battery Park Tower,Residential Building (Apartment / Condo),50 Lynn Williams St,43.639024,-79.415510,M6K 3R9,ON
20,GoodLife Fitness Toronto Bloor Park,Gym,8 Park Rd,43.671398,-79.384408,M4W 3G8,ON
21,Riverdale Park East,Park,550 Broadview Ave,43.669951,-79.355493,M4K 2P1,ON
25,Victoria Park Subway Station,Metro Station,777 Victoria Park Ave,43.694883,-79.288735,M4B 2E2,ON
26,Coronation Park,Park,711 Lake Shore Blvd. W,43.634553,-79.405403,M5V 3T7,ON
27,Canoe Landing Park,Park,50 Fort York Blvd,43.638762,-79.397067,M5V 3Z1,ON
28,Barbara Hall Park,Park,519 Church St,43.666879,-79.381068,M4Y 2K9,ON

In [20]:
# delete rows which its category is not Park
df_park = clean_park_dataframe3[clean_park_dataframe3.categories == 'Park']
df_park

,name,categories,address,lat,lng,postalCode,state
4,Trinity Bellwoods Park,Park,1053 Dundas St. W.,43.647072,-79.413756,M5H 2N2,ON
6,Queen's Park,Park,University Ave.,43.663946,-79.392180,M5R 2E8,ON
8,Bellevue Square Park,Park,btwn Bellevue & Augusta Ave.,43.653610,-79.402199,M5T 2N4,ON
12,High Park,Park,1873 Bloor St. W,43.646479,-79.463425,M6R 2Z3,ON
18,Riverdale Park West,Park,500 Gerrard St.,43.666048,-79.360941,M5A 2H3,ON
21,Riverdale Park East,Park,550 Broadview Ave,43.669951,-79.355493,M4K 2P1,ON
26,Coronation Park,Park,711 Lake Shore Blvd. W,43.634553,-79.405403,M5V 3T7,ON
27,Canoe Landing Park,Park,50 Fort York Blvd,43.638762,-79.397067,M5V 3Z1,ON
28,Barbara Hall Park,Park,519 Church St,43.666879,-79.381068,M4Y 2K9,ON

## **Search for Restaurants**

In [21]:
# search for Restaurants
search_query = 'Restaurant'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK&client_secret=AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG&ll=43.653963,-79.387207&v=20180604&query=Restaurant&radius=10000&limit=30'

In [22]:
# Send the GET Request and examine the results
Rresults = requests.get(url).json()
#Rresults

In [23]:
# assign relevant part of JSON to venues
venues = Rresults['response']['venues']

# tranform venues into a dataframe
Restaurant_dataframe = json_normalize(venues)
Restaurant_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId,venuePage.id
0,"[{'name': 'American Restaurant', 'pluralName':...",False,4ad4c05ff964a52048f720e3,110 Chestnut Street,CA,Toronto,Canada,NaN,145,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]","[{'lat': 43.65488413420439, 'label': 'display'...",43.654884,-79.385931,NaN,M5G 1R3,ON,Hemispheres Restaurant & Bistro,v-1558854633,NaN
1,"[{'name': 'Dim Sum Restaurant', 'pluralName': ...",False,4ad4c060f964a5207ff720e3,323 Spadina Ave.,CA,Toronto,Canada,at D'Arcy St.,922,"[323 Spadina Ave. (at D'Arcy St.), Toronto ON ...","[{'lat': 43.65431754076345, 'label': 'display'...",43.654318,-79.398650,Kensington Market,M5T 2E9,ON,Rol San Restaurant 龍笙棧,v-1558854633,NaN
2,"[{'name': 'Noodle House', 'pluralName': 'Noodl...",False,4b266f05f964a520657b24e3,266 Spadina Ave,CA,Toronto,Canada,at Willison Sq,892,"[266 Spadina Ave (at Willison Sq), Toronto ON ...","[{'lat': 43.6522783893466, 'label': 'display',...",43.652278,-79.398039,NaN,M5T 2E4,ON,Goldstone Noodle Restaurant 金石,v-1558854633,NaN
3,"[{'name': 'Wine Bar', 'pluralName': 'Wine Bars...",False,4ad4c05cf964a520dff520e3,301 Front St W,CA,Toronto,Canada,301 Front St. W,1271,"[301 Front St W (301 Front St. W), Toronto ON ...","[{'lat': 43.642537317144566, 'label': 'display...",43.642537,-79.387042,NaN,M5V 2T6,ON,360 Restaurant,v-1558854633,NaN
4,"[{'name': 'Chinese Restaurant', 'pluralName': ...",False,4ae29812f964a520288f21e3,309 Spadina Ave.,CA,Toronto,Canada,btwn Dundas St. W & D'Arcy St.,896,[309 Spadina Ave. (btwn Dundas St. W & D'Arcy ...,"[{'lat': 43.65386562507761, 'label': 'display'...",43.653866,-79.398334,NaN,M5T 2E6,ON,Swatow Restaurant 汕頭小食家,v-1558854633,NaN

## **Clean Restaurant Dataframe**

In [24]:
# keep only columns that include venue name, and anything that is associated with location
Restaurant_clean_columns = ['name', 'categories'] + [col for col in Restaurant_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Restaurant_dataframe = Restaurant_dataframe.loc[:,Restaurant_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list3 = row['categories']
    except:
        categories_list3 = row['venue.categories']
        
    if len(categories_list3) == 0:
        return None
    else:
        return categories_list3[0]['name']

# filter the category for each row
clean_Restaurant_dataframe['categories'] = clean_Restaurant_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Restaurant_dataframe.columns = [column.split('.')[-1] for column in clean_Restaurant_dataframe.columns]

clean_Restaurant_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,neighborhood,postalCode,state,id
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,CA,Toronto,Canada,NaN,145,"[110 Chestnut Street, Toronto ON M5G 1R3, Canada]","[{'lat': 43.65488413420439, 'label': 'display'...",43.654884,-79.385931,NaN,M5G 1R3,ON,4ad4c05ff964a52048f720e3
1,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,CA,Toronto,Canada,at D'Arcy St.,922,"[323 Spadina Ave. (at D'Arcy St.), Toronto ON ...","[{'lat': 43.65431754076345, 'label': 'display'...",43.654318,-79.398650,Kensington Market,M5T 2E9,ON,4ad4c060f964a5207ff720e3
2,Goldstone Noodle Restaurant 金石,Noodle House,266 Spadina Ave,CA,Toronto,Canada,at Willison Sq,892,"[266 Spadina Ave (at Willison Sq), Toronto ON ...","[{'lat': 43.6522783893466, 'label': 'display',...",43.652278,-79.398039,NaN,M5T 2E4,ON,4b266f05f964a520657b24e3
3,360 Restaurant,Wine Bar,301 Front St W,CA,Toronto,Canada,301 Front St. W,1271,"[301 Front St W (301 Front St. W), Toronto ON ...","[{'lat': 43.642537317144566, 'label': 'display...",43.642537,-79.387042,NaN,M5V 2T6,ON,4ad4c05cf964a520dff520e3
4,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,CA,Toronto,Canada,btwn Dundas St. W & D'Arcy St.,896,[309 Spadina Ave. (btwn Dundas St. W & D'Arcy ...,"[{'lat': 43.65386562507761, 'label': 'display'...",43.653866,-79.398334,NaN,M5T 2E6,ON,4ae29812f964a520288f21e3

In [25]:
# delete unnecessary columns
clean_Restaurant_dataframe2= clean_Restaurant_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'neighborhood', 'id'], axis=1)
clean_Restaurant_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,M5G 1R3,ON
1,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,43.654318,-79.398650,M5T 2E9,ON
2,Goldstone Noodle Restaurant 金石,Noodle House,266 Spadina Ave,43.652278,-79.398039,M5T 2E4,ON
3,360 Restaurant,Wine Bar,301 Front St W,43.642537,-79.387042,M5V 2T6,ON
4,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,43.653866,-79.398334,M5T 2E6,ON
5,Sky Dragon Chinese Restaurant 龍翔酒樓,Dim Sum Restaurant,280 Spadina Ave.,43.652783,-79.398174,NaN,ON
6,Victoria's Restaurant,Restaurant,37 King Street East,43.649298,-79.376431,M5C 1E9,ON
7,New Sky Restaurant 小沙田食家,Chinese Restaurant,353 Spadina Ave.,43.655337,-79.398897,M5T 2G3,ON
8,Azure Restaurant & Bar,Restaurant,225 Frnt St W,43.644749,-79.385113,M5V 2X3,ON
9,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,M5G 1C7,ON
10,Victor Restaurant & Bar,Bar,30 Mercer Street,43.645634,-79.391125,M5V 1H3,ON
11,North-East Chinese Restaurant 華北美食,Chinese Restaurant,476 Dundas St.,43.653185,-79.396677,NaN,ON
12,Sassafraz | Cafe | Restaurant | Private Events,Event Space,100 Cumberland Street,43.670342,-79.391041,M5R 1A6,ON
13,The Hot House Restaurant & Bar,American Restaurant,35 Church St,43.648824,-79.373702,M5E 1T3,ON
14,Aroma Fine Indian Restaurant,Indian Restaurant,287 King St. W,43.646463,-79.389644,M5V 1J5,ON
15,The Lakeview Restaurant,Diner,1132 Dundas St. W,43.649435,-79.420390,M6J 1X2,ON
16,Insomnia Restaurant and Lounge,Restaurant,563 Bloor St West,43.665180,-79.410966,M5S 1Y6,ON
17,El Rancho Restaurant & Night Club,Nightclub,430 College St.,43.656673,-79.407101,M5T 1T3,ON
18,Ka Chi Korean Restaurant,Korean Restaurant,8 St Andrew St.,43.654307,-79.399277,M5T 1K6,ON
19,Woodlot Restaurant & Bakery,New American Restaurant,293 Palmerston Ave.,43.655765,-79.409929,M6J 2J3,ON
20,Green Tea Restaurant,Chinese Restaurant,261 Spadina Ave,43.652309,-79.397603,M5T 2E3,ON
21,Montecito Restaurant,Restaurant,299 Adelaide St W,43.647644,-79.391069,M5V 1P7,ON
22,ONE Restaurant/Lounge,New American Restaurant,116 Yorkville Ave,43.670809,-79.393272,NaN,ON
23,Tundra Restaurant,Restaurant,145 Richmond Street West,43.650010,-79.385608,M5H 2L2,ON
24,Bright Pearl Seafood Restaurant,Chinese Restaurant,346-348 Spadina Avenue,43.654219,-79.399125,M5T 2G2,ON
25,Matisse Restaurant And Bar,Restaurant,90 Bloor St.,43.670574,-79.384856,M4W 1A7,ON
26,Tasty's Caribbean Restaurant & Catering,Caribbean Restaurant,405 Spadina Ave,43.656794,-79.399251,M5T 2G6,ON
27,Studio Restaurant,Breakfast Spot,389 Church St.,43.661500,-79.379319,M5B,ON
28,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,M5H 3X4,ON
29,Union Restaurant,New American Restaurant,72 Ossington Ave.,43.645860,-79.419532,NaN,ON

In [26]:
# delete rows with none values
df_Restaurant = clean_Restaurant_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
df_Restaurant

,name,categories,address,lat,lng,postalCode,state
0,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,M5G 1R3,ON
1,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,43.654318,-79.398650,M5T 2E9,ON
2,Goldstone Noodle Restaurant 金石,Noodle House,266 Spadina Ave,43.652278,-79.398039,M5T 2E4,ON
3,360 Restaurant,Wine Bar,301 Front St W,43.642537,-79.387042,M5V 2T6,ON
4,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,43.653866,-79.398334,M5T 2E6,ON
6,Victoria's Restaurant,Restaurant,37 King Street East,43.649298,-79.376431,M5C 1E9,ON
7,New Sky Restaurant 小沙田食家,Chinese Restaurant,353 Spadina Ave.,43.655337,-79.398897,M5T 2G3,ON
8,Azure Restaurant & Bar,Restaurant,225 Frnt St W,43.644749,-79.385113,M5V 2X3,ON
9,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,M5G 1C7,ON
10,Victor Restaurant & Bar,Bar,30 Mercer Street,43.645634,-79.391125,M5V 1H3,ON
12,Sassafraz | Cafe | Restaurant | Private Events,Event Space,100 Cumberland Street,43.670342,-79.391041,M5R 1A6,ON
13,The Hot House Restaurant & Bar,American Restaurant,35 Church St,43.648824,-79.373702,M5E 1T3,ON
14,Aroma Fine Indian Restaurant,Indian Restaurant,287 King St. W,43.646463,-79.389644,M5V 1J5,ON
15,The Lakeview Restaurant,Diner,1132 Dundas St. W,43.649435,-79.420390,M6J 1X2,ON
16,Insomnia Restaurant and Lounge,Restaurant,563 Bloor St West,43.665180,-79.410966,M5S 1Y6,ON
17,El Rancho Restaurant & Night Club,Nightclub,430 College St.,43.656673,-79.407101,M5T 1T3,ON
18,Ka Chi Korean Restaurant,Korean Restaurant,8 St Andrew St.,43.654307,-79.399277,M5T 1K6,ON
19,Woodlot Restaurant & Bakery,New American Restaurant,293 Palmerston Ave.,43.655765,-79.409929,M6J 2J3,ON
20,Green Tea Restaurant,Chinese Restaurant,261 Spadina Ave,43.652309,-79.397603,M5T 2E3,ON
21,Montecito Restaurant,Restaurant,299 Adelaide St W,43.647644,-79.391069,M5V 1P7,ON
23,Tundra Restaurant,Restaurant,145 Richmond Street West,43.650010,-79.385608,M5H 2L2,ON
24,Bright Pearl Seafood Restaurant,Chinese Restaurant,346-348 Spadina Avenue,43.654219,-79.399125,M5T 2G2,ON
25,Matisse Restaurant And Bar,Restaurant,90 Bloor St.,43.670574,-79.384856,M4W 1A7,ON
26,Tasty's Caribbean Restaurant & Catering,Caribbean Restaurant,405 Spadina Ave,43.656794,-79.399251,M5T 2G6,ON
27,Studio Restaurant,Breakfast Spot,389 Church St.,43.661500,-79.379319,M5B,ON
28,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,M5H 3X4,ON

## **Search for Cafeteria**

In [27]:
# search for Cafeteria
search_query = 'Cafeteria'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK&client_secret=AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG&ll=43.653963,-79.387207&v=20180604&query=Cafeteria&radius=10000&limit=30'

In [28]:
# Send the GET Request and examine the results
cresults = requests.get(url).json()
#cresults

In [29]:
# assign relevant part of JSON to venues
venues = cresults['response']['venues']

# tranform venues into a dataframe
Cafeteria_dataframe = json_normalize(venues)
Cafeteria_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId
0,"[{'name': 'Fast Food Restaurant', 'pluralName'...",False,4f9165bde4b04fef0087e4e2,The Hospital for Sick Children (SickKids),CA,Toronto,Canada,NaN,372,"[The Hospital for Sick Children (SickKids), To...","[{'lat': 43.65720930549997, 'label': 'display'...",43.657209,-79.386063,NaN,ON,Cafeteria,v-1558854656
1,"[{'name': 'Asian Restaurant', 'pluralName': 'A...",False,528e99a211d262edc3708a6f,388 Spadina Ave,CA,Toronto,Canada,at Nassau St,977,"[388 Spadina Ave (at Nassau St), Toronto ON M5...","[{'lat': 43.65545427446646, 'label': 'display'...",43.655454,-79.399163,M5T 2G5,ON,Stay Cafeteria 慢走,v-1558854656
2,"[{'name': 'Mexican Restaurant', 'pluralName': ...",False,56b2c90a498e9f0e73d6bed6,974 College St,CA,Toronto,Canada,NaN,3260,"[974 College St, Toronto ON M6H 1A5, Canada]","[{'lat': 43.65341883567197, 'label': 'display'...",43.653419,-79.427678,M6H 1A5,ON,Cafeteria,v-1558854656
3,"[{'name': 'Cafeteria', 'pluralName': 'Cafeteri...",False,53bd6dfe498e6c1d3bc9333e,NaN,CA,Toronto,Canada,NaN,260,"[Toronto ON, Canada]","[{'lat': 43.655657, 'label': 'display', 'lng':...",43.655657,-79.389443,NaN,ON,Industrial Alliance Cafeteria,v-1558854656
4,"[{'name': 'Dessert Shop', 'pluralName': 'Desse...",False,556f826b498e07f469e6bf1f,NaN,CA,NaN,Canada,NaN,431,[Canada],"[{'lat': 43.654178619384766, 'label': 'display...",43.654179,-79.392555,NaN,NaN,Dears Cafeteria,v-1558854656

## **Clean Cafeteria Dataframe**

In [30]:
# keep only columns that include venue name, and anything that is associated with location
Cafeteria_clean_columns = ['name', 'categories'] + [col for col in Cafeteria_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Cafeteria_dataframe = Cafeteria_dataframe.loc[:,Cafeteria_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list4 = row['categories']
    except:
        categories_list4 = row['venue.categories']
        
    if len(categories_list4) == 0:
        return None
    else:
        return categories_list4[0]['name']

# filter the category for each row
clean_Cafeteria_dataframe['categories'] = clean_Cafeteria_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Cafeteria_dataframe.columns = [column.split('.')[-1] for column in clean_Cafeteria_dataframe.columns]

clean_Cafeteria_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,Cafeteria,Fast Food Restaurant,The Hospital for Sick Children (SickKids),CA,Toronto,Canada,NaN,372,"[The Hospital for Sick Children (SickKids), To...","[{'lat': 43.65720930549997, 'label': 'display'...",43.657209,-79.386063,NaN,ON,4f9165bde4b04fef0087e4e2
1,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,CA,Toronto,Canada,at Nassau St,977,"[388 Spadina Ave (at Nassau St), Toronto ON M5...","[{'lat': 43.65545427446646, 'label': 'display'...",43.655454,-79.399163,M5T 2G5,ON,528e99a211d262edc3708a6f
2,Cafeteria,Mexican Restaurant,974 College St,CA,Toronto,Canada,NaN,3260,"[974 College St, Toronto ON M6H 1A5, Canada]","[{'lat': 43.65341883567197, 'label': 'display'...",43.653419,-79.427678,M6H 1A5,ON,56b2c90a498e9f0e73d6bed6
3,Industrial Alliance Cafeteria,Cafeteria,NaN,CA,Toronto,Canada,NaN,260,"[Toronto ON, Canada]","[{'lat': 43.655657, 'label': 'display', 'lng':...",43.655657,-79.389443,NaN,ON,53bd6dfe498e6c1d3bc9333e
4,Dears Cafeteria,Dessert Shop,NaN,CA,NaN,Canada,NaN,431,[Canada],"[{'lat': 43.654178619384766, 'label': 'display...",43.654179,-79.392555,NaN,NaN,556f826b498e07f469e6bf1f

In [32]:
# delete unnecessary columns
clean_Cafeteria_dataframe2= clean_Cafeteria_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_Cafeteria_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Cafeteria,Fast Food Restaurant,The Hospital for Sick Children (SickKids),43.657209,-79.386063,NaN,ON
1,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,M5T 2G5,ON
2,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,M6H 1A5,ON
3,Industrial Alliance Cafeteria,Cafeteria,NaN,43.655657,-79.389443,NaN,ON
4,Dears Cafeteria,Dessert Shop,NaN,43.654179,-79.392555,NaN,NaN
5,OCAD Cafeteria,College Cafeteria,100 McCaul St.,43.652780,-79.391762,NaN,ON
6,Chestnut Tree Cafeteria,Cafeteria,89 Chestnut Street,43.648231,-79.384045,NaN,ON
7,Sears Cafeteria,Food Court,Yonge,43.656038,-79.380672,NaN,ON
8,De La Salle College Cafeteria,College Cafeteria,131 Farnham Avenue,43.683003,-79.397815,M4V 1H7,ON
9,Med Sci Cafeteria,College Cafeteria,NaN,43.660260,-79.392977,NaN,ON
10,Ryerson Hub Cafeteria,College Cafeteria,350 Victoria St.,43.658475,-79.377653,NaN,ON
11,SickKids Cafeteria,Food Court,555 University Avenue,43.657584,-79.375652,NaN,ON
12,Macdonald Block Cafeteria,Cafeteria,NaN,43.663212,-79.388062,NaN,NaN
13,Robarts Cafeteria,College Cafeteria,130 St. George St.,43.664864,-79.399766,NaN,ON
14,OMP Cafeteria,Cafeteria,1 Mount Pleasant,43.669801,-79.379790,NaN,ON
15,Rogers Cafeteria,Food Court,NaN,43.669904,-79.379748,NaN,ON
16,Choices Cafeteria,Food Court,200 Bloor Street E,43.671411,-79.381849,NaN,ON
17,"Cafeteria, Lawrence Park Collegiate",High School,NaN,43.721732,-79.409600,NaN,NaN
18,Kasala Cafeteria,African Restaurant,Bloor,43.660759,-79.424018,NaN,NaN
19,"Cafeteria, Lawrence Park Collegiate",Event Space,NaN,43.723286,-79.412222,NaN,NaN
20,The Hub,College Cafeteria,350 Victoria St.,43.658585,-79.380622,M5B 2K3,ON
21,Estonian House Cafeteria,Café,958 Broadview avenue,43.681763,-79.358246,NaN,ON
22,Marketeria,Restaurant,30 Bond St.,43.653585,-79.378843,M5B 1W8,ON
23,CC Cafeteria,College Cafeteria,951 Carlaw Ave,43.684631,-79.348862,NaN,ON
24,Radio Cafe,Food Court,333 Bloor st east,43.671696,-79.380617,NaN,ON
25,One Hour,Chinese Restaurant,435 Spadina Ave.,43.657399,-79.399649,M5T 2T6,ON
26,Innis College,Student Center,2 Sussex Ave,43.665556,-79.399298,M5S 1J5,ON
27,Lawrence Park Collegiate Cafeteria,High School,NaN,43.722757,-79.413734,NaN,ON
28,L5 Cafeteria,Cuban Restaurant,NaN,43.723019,-79.345012,NaN,NaN
29,6th Floor Cafeteria 12 Concorde Place,Café,12 Concorde Place,43.721861,-79.329339,m3c 3k7,ON

In [33]:
# delete rows with none values
df_Cafeteria = clean_Cafeteria_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
df_Cafeteria

,name,categories,address,lat,lng,postalCode,state
1,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,M5T 2G5,ON
2,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,M6H 1A5,ON
8,De La Salle College Cafeteria,College Cafeteria,131 Farnham Avenue,43.683003,-79.397815,M4V 1H7,ON
20,The Hub,College Cafeteria,350 Victoria St.,43.658585,-79.380622,M5B 2K3,ON
22,Marketeria,Restaurant,30 Bond St.,43.653585,-79.378843,M5B 1W8,ON
25,One Hour,Chinese Restaurant,435 Spadina Ave.,43.657399,-79.399649,M5T 2T6,ON
26,Innis College,Student Center,2 Sussex Ave,43.665556,-79.399298,M5S 1J5,ON
29,6th Floor Cafeteria 12 Concorde Place,Café,12 Concorde Place,43.721861,-79.329339,m3c 3k7,ON

## **Search for Shopping Stores**

In [34]:
# search for Shopping
search_query = 'Shopping'
radius = 1000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=4V5UKCUV3SI2BUIXWEYAVEUZUF2SBKKWN2BCNXAEBZCAUUAK&client_secret=AUWDUQ4MOTJB2SANW5I21ZEPKRXXWTMTLBVUJLM2LWW4XEEG&ll=43.653963,-79.387207&v=20180604&query=Shopping&radius=1000&limit=30'

In [35]:
# Send the GET Request and examine the results
sresults = requests.get(url).json()
#sresults

In [36]:
# assign relevant part of JSON to venues
venues = sresults['response']['venues']

# tranform venues into a dataframe
Shopping_dataframe = json_normalize(venues)
Shopping_dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.neighborhood,location.postalCode,location.state,name,referralId
0,"[{'name': 'Shopping Mall', 'pluralName': 'Shop...",False,4ad4c062f964a520fcf720e3,280 Spadina Ave,CA,Toronto,Canada,at Dundas St W,897,"[280 Spadina Ave (at Dundas St W), Toronto ON ...","[{'lat': 43.65277367198862, 'label': 'display'...",43.652774,-79.398222,NaN,M5T 3A5,ON,Dragon City Shopping Mall 龍城,v-1558854712
1,"[{'name': 'Shopping Mall', 'pluralName': 'Shop...",False,4ad77a12f964a520260b21e3,220 Yonge St,CA,Toronto,Canada,btwn Queen & Dundas,535,"[220 Yonge St (btwn Queen & Dundas), Toronto O...",NaN,43.653810,-79.380562,"Downtown Toronto, Toronto, ON",M5B 2H1,ON,CF Toronto Eaton Centre,v-1558854712
2,"[{'name': 'Shopping Mall', 'pluralName': 'Shop...",False,4b9e86dff964a520e6eb36e3,66 Wellington St W,CA,Toronto,Canada,btw York & Bay St,908,"[66 Wellington St W (btw York & Bay St), Toron...","[{'lat': 43.64718424611984, 'label': 'display'...",43.647184,-79.380932,NaN,M5K 1A1,ON,TD Centre Shopping Concourse,v-1558854712
3,"[{'name': 'Department Store', 'pluralName': 'D...",False,5840cafe06f1a34af80cc609,176 Yonge Street,CA,Toronto,Canada,Queen Street West,688,"[176 Yonge Street (Queen Street West), Toronto...","[{'lat': 43.65181, 'label': 'display', 'lng': ...",43.651810,-79.379192,NaN,M5C 2L7,ON,Saks Fifth Avenue Club - Personal Shopping,v-1558854712
4,"[{'name': 'Office', 'pluralName': 'Offices', '...",False,4b83d653f964a520d91231e3,461 King St. West,CA,Toronto,Canada,NaN,974,"[461 King St. West, Toronto ON M5V 1K4, Canada]","[{'lat': 43.64795765580337, 'label': 'display'...",43.647958,-79.396006,NaN,M5V 1K4,ON,Yellow Pages - RedFlagDeals.com,v-1558854712

## **Clean Shopping Dataframe**

In [37]:
# keep only columns that include venue name, and anything that is associated with location
Shopping_clean_columns = ['name', 'categories'] + [col for col in Shopping_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Shopping_dataframe = Shopping_dataframe.loc[:,Shopping_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list5 = row['categories']
    except:
        categories_list5 = row['venue.categories']
        
    if len(categories_list5) == 0:
        return None
    else:
        return categories_list5[0]['name']

# filter the category for each row
clean_Shopping_dataframe['categories'] = clean_Shopping_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Shopping_dataframe.columns = [column.split('.')[-1] for column in clean_Shopping_dataframe.columns]

clean_Shopping_dataframe.head()

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,neighborhood,postalCode,state,id
0,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,CA,Toronto,Canada,at Dundas St W,897,"[280 Spadina Ave (at Dundas St W), Toronto ON ...","[{'lat': 43.65277367198862, 'label': 'display'...",43.652774,-79.398222,NaN,M5T 3A5,ON,4ad4c062f964a520fcf720e3
1,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,CA,Toronto,Canada,btwn Queen & Dundas,535,"[220 Yonge St (btwn Queen & Dundas), Toronto O...",NaN,43.653810,-79.380562,"Downtown Toronto, Toronto, ON",M5B 2H1,ON,4ad77a12f964a520260b21e3
2,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,CA,Toronto,Canada,btw York & Bay St,908,"[66 Wellington St W (btw York & Bay St), Toron...","[{'lat': 43.64718424611984, 'label': 'display'...",43.647184,-79.380932,NaN,M5K 1A1,ON,4b9e86dff964a520e6eb36e3
3,Saks Fifth Avenue Club - Personal Shopping,Department Store,176 Yonge Street,CA,Toronto,Canada,Queen Street West,688,"[176 Yonge Street (Queen Street West), Toronto...","[{'lat': 43.65181, 'label': 'display', 'lng': ...",43.651810,-79.379192,NaN,M5C 2L7,ON,5840cafe06f1a34af80cc609
4,Yellow Pages - RedFlagDeals.com,Office,461 King St. West,CA,Toronto,Canada,NaN,974,"[461 King St. West, Toronto ON M5V 1K4, Canada]","[{'lat': 43.64795765580337, 'label': 'display'...",43.647958,-79.396006,NaN,M5V 1K4,ON,4b83d653f964a520d91231e3

In [38]:
# delete unnecessary columns
clean_Shopping_dataframe2= clean_Shopping_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'neighborhood', 'id'], axis=1)
clean_Shopping_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,43.652774,-79.398222,M5T 3A5,ON
1,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,43.653810,-79.380562,M5B 2H1,ON
2,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,43.647184,-79.380932,M5K 1A1,ON
3,Saks Fifth Avenue Club - Personal Shopping,Department Store,176 Yonge Street,43.651810,-79.379192,M5C 2L7,ON
4,Yellow Pages - RedFlagDeals.com,Office,461 King St. West,43.647958,-79.396006,M5V 1K4,ON

In [39]:
# delete rows which its category is not Shopping Mall
df_Shopping = clean_Shopping_dataframe2[clean_Shopping_dataframe2.categories == 'Shopping Mall']
df_Shopping

,name,categories,address,lat,lng,postalCode,state
0,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,43.652774,-79.398222,M5T 3A5,ON
1,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,43.653810,-79.380562,M5B 2H1,ON
2,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,43.647184,-79.380932,M5K 1A1,ON

## **Generate map to visualize hotels, shopping stores and Cafeteria and how they cluster together**

In [40]:
# create dataframe of hotels, shopping stores and Cafeteria
hotel_neighbourhood_df = pd.concat([df_hotel, df_Cafeteria, df_Shopping], ignore_index=True)
hotel_neighbourhood_df

,name,categories,address,lat,lng,postalCode,state
0,Sheraton Centre Toronto Hotel,Hotel,123 Queen Street West,43.651129,-79.383829,M5H 2M9,ON
1,Grand Ballroom,Event Space,123 Queen St. W,43.651217,-79.383771,M5H 2M9,ON
2,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,M5T 2G5,ON
3,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,M6H 1A5,ON
4,De La Salle College Cafeteria,College Cafeteria,131 Farnham Avenue,43.683003,-79.397815,M4V 1H7,ON
5,The Hub,College Cafeteria,350 Victoria St.,43.658585,-79.380622,M5B 2K3,ON
6,Marketeria,Restaurant,30 Bond St.,43.653585,-79.378843,M5B 1W8,ON
7,One Hour,Chinese Restaurant,435 Spadina Ave.,43.657399,-79.399649,M5T 2T6,ON
8,Innis College,Student Center,2 Sussex Ave,43.665556,-79.399298,M5S 1J5,ON
9,6th Floor Cafeteria 12 Concorde Place,Café,12 Concorde Place,43.721861,-79.329339,m3c 3k7,ON
10,Dragon City Shopping Mall 龍城,Shopping Mall,280 Spadina Ave,43.652774,-79.398222,M5T 3A5,ON
11,CF Toronto Eaton Centre,Shopping Mall,220 Yonge St,43.653810,-79.380562,M5B 2H1,ON
12,TD Centre Shopping Concourse,Shopping Mall,66 Wellington St W,43.647184,-79.380932,M5K 1A1,ON

In [41]:
# Generate map to visualize hotel neighbourhood including shopping stores and Cafeteria 
hotel_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(hotel_neighbourhood_df['lat'], hotel_neighbourhood_df['lng'], 
                                           hotel_neighbourhood_df['name'], hotel_neighbourhood_df['categories'],\
                                               hotel_neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(hotel_map)  
    
hotel_map

## **Generate map to visualize Park, Restaurant and Cafeteria and how they cluster together**

In [42]:
# create dataframe of Park, Restaurant and Cafeteria
park_neighbourhood_df = pd.concat([df_park, df_Restaurant, df_Cafeteria,], ignore_index=True)
park_neighbourhood_df

,name,categories,address,lat,lng,postalCode,state
0,Trinity Bellwoods Park,Park,1053 Dundas St. W.,43.647072,-79.413756,M5H 2N2,ON
1,Queen's Park,Park,University Ave.,43.663946,-79.392180,M5R 2E8,ON
2,Bellevue Square Park,Park,btwn Bellevue & Augusta Ave.,43.653610,-79.402199,M5T 2N4,ON
3,High Park,Park,1873 Bloor St. W,43.646479,-79.463425,M6R 2Z3,ON
4,Riverdale Park West,Park,500 Gerrard St.,43.666048,-79.360941,M5A 2H3,ON
5,Riverdale Park East,Park,550 Broadview Ave,43.669951,-79.355493,M4K 2P1,ON
6,Coronation Park,Park,711 Lake Shore Blvd. W,43.634553,-79.405403,M5V 3T7,ON
7,Canoe Landing Park,Park,50 Fort York Blvd,43.638762,-79.397067,M5V 3Z1,ON
8,Barbara Hall Park,Park,519 Church St,43.666879,-79.381068,M4Y 2K9,ON
9,Hemispheres Restaurant & Bistro,American Restaurant,110 Chestnut Street,43.654884,-79.385931,M5G 1R3,ON
10,Rol San Restaurant 龍笙棧,Dim Sum Restaurant,323 Spadina Ave.,43.654318,-79.398650,M5T 2E9,ON
11,Goldstone Noodle Restaurant 金石,Noodle House,266 Spadina Ave,43.652278,-79.398039,M5T 2E4,ON
12,360 Restaurant,Wine Bar,301 Front St W,43.642537,-79.387042,M5V 2T6,ON
13,Swatow Restaurant 汕頭小食家,Chinese Restaurant,309 Spadina Ave.,43.653866,-79.398334,M5T 2E6,ON
14,Victoria's Restaurant,Restaurant,37 King Street East,43.649298,-79.376431,M5C 1E9,ON
15,New Sky Restaurant 小沙田食家,Chinese Restaurant,353 Spadina Ave.,43.655337,-79.398897,M5T 2G3,ON
16,Azure Restaurant & Bar,Restaurant,225 Frnt St W,43.644749,-79.385113,M5V 2X3,ON
17,Hong Shing Chinese Restaurant,Chinese Restaurant,195 Dundas St W,43.654925,-79.387089,M5G 1C7,ON
18,Victor Restaurant & Bar,Bar,30 Mercer Street,43.645634,-79.391125,M5V 1H3,ON
19,Sassafraz | Cafe | Restaurant | Private Events,Event Space,100 Cumberland Street,43.670342,-79.391041,M5R 1A6,ON
20,The Hot House Restaurant & Bar,American Restaurant,35 Church St,43.648824,-79.373702,M5E 1T3,ON
21,Aroma Fine Indian Restaurant,Indian Restaurant,287 King St. W,43.646463,-79.389644,M5V 1J5,ON
22,The Lakeview Restaurant,Diner,1132 Dundas St. W,43.649435,-79.420390,M6J 1X2,ON
23,Insomnia Restaurant and Lounge,Restaurant,563 Bloor St West,43.665180,-79.410966,M5S 1Y6,ON
24,El Rancho Restaurant & Night Club,Nightclub,430 College St.,43.656673,-79.407101,M5T 1T3,ON
25,Ka Chi Korean Restaurant,Korean Restaurant,8 St Andrew St.,43.654307,-79.399277,M5T 1K6,ON
26,Woodlot Restaurant & Bakery,New American Restaurant,293 Palmerston Ave.,43.655765,-79.409929,M6J 2J3,ON
27,Green Tea Restaurant,Chinese Restaurant,261 Spadina Ave,43.652309,-79.397603,M5T 2E3,ON
28,Montecito Restaurant,Restaurant,299 Adelaide St W,43.647644,-79.391069,M5V 1P7,ON
29,Tundra Restaurant,Restaurant,145 Richmond Street West,43.650010,-79.385608,M5H 2L2,ON
30,Bright Pearl Seafood Restaurant,Chinese Restaurant,346-348 Spadina Avenue,43.654219,-79.399125,M5T 2G2,ON
31,Matisse Restaurant And Bar,Restaurant,90 Bloor St.,43.670574,-79.384856,M4W 1A7,ON
32,Tasty's Caribbean Restaurant & Catering,Caribbean Restaurant,405 Spadina Ave,43.656794,-79.399251,M5T 2G6,ON
33,Studio Restaurant,Breakfast Spot,389 Church St.,43.661500,-79.379319,M5B,ON
34,Richtree Natural Market Restaurants,Restaurant,14 Queen St W,43.652614,-79.380231,M5H 3X4,ON
35,Stay Cafeteria 慢走,Asian Restaurant,388 Spadina Ave,43.655454,-79.399163,M5T 2G5,ON
36,Cafeteria,Mexican Restaurant,974 College St,43.653419,-79.427678,M6H 1A5,ON
37,De La Salle College Cafeteria,College Cafeteria,131 Farnham Avenue,43.683003,-79.397815,M4V 1H7,ON
38,The Hub,College Cafeteria,350 Victoria St.,43.658585,-79.380622,M5B 2K3,ON
39,Marketeria,Restaurant,30 Bond St.,43.653585,-79.378843,M5B 1W8,ON
40,One Hour,Chinese Restaurant,435 Spadina Ave.,43.657399,-79.399649,M5T 2T6,ON
41,Innis College,Student Center,2 Sussex Ave,43.665556,-79.399298,M5S 1J5,ON
42,6th Floor Cafeteria 12 Concorde Place,Café,12 Concorde Place,43.721861,-79.329339,m3c 3k7,ON

In [43]:
# Generate map to visualize park neighbourhood including Restaurant and Cafeteria 
park_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(park_neighbourhood_df['lat'], park_neighbourhood_df['lng'], 
                                           park_neighbourhood_df['name'], park_neighbourhood_df['categories'],\
                                               park_neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(park_map)  
    
park_map